name: Build and Release Plugin

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test

    - name: Build plugin
      run: ./gradlew buildPlugin

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: plugin-dist
        path: build/distributions/*.zip

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: build/distributions/*.zip
        generate_release_notes: true

    - name: Publish Plugin
      if: startsWith(github.ref, 'refs/tags/v')
      run: ./gradlew publishPlugin
      env:
        INTELLIJ_PUBLISH_TOKEN: ${{ secrets.INTELLIJ_PUBLISH_TOKEN }} 